Repository vechain/thor, pull requests merged in 2024-07, with the labels that each got.

#779 use uint64 for number flags
  cmd/thor/flags.go
  cmd/thor/main.go
  cmd/thor/utils.go
Labels: enhancement

#782 Increase consensus coverage to +85%
  consensus/consensus_test.go
Labels: testing

#787 Tweaking unit test batches
  api/accounts/accounts_test.go
  api/blocks/blocks_test.go
  api/debug/debug_test.go
  api/events/events_test.go
  api/events/types_test.go
  api/subscriptions/subscriptions_test.go
  api/transactions/transactions_test.go
  trie/proof_test.go
Labels: testing

#781 Darren/enhancement/use slog
  api/api.go
  api/request_logger.go
  api/request_logger_test.go
  api/subscriptions/block_reader_test.go
  api/subscriptions/subscriptions.go
  api/transactions/transactions_test.go
  block/header_test.go
  cache/prio_cache_test.go
  cache/rnd_cache.go
  cmd/disco/VERSION
  cmd/disco/flags.go
  cmd/disco/main.go
  cmd/disco/utils.go
  cmd/thor/flags.go
  cmd/thor/main.go
  cmd/thor/node/node.go
  cmd/thor/node/packer_loop.go
  cmd/thor/node/tx_stash.go
  cmd/thor/optimizer/optimizer.go
  cmd/thor/optimizer/optimizer_test.go
  cmd/thor/solo/solo.go
  cmd/thor/utils.go
  comm/communicator.go
  comm/peer.go
  go.mod
  go.sum
  log/README.md
  log/format.go
  log/format_test.go
  log/handler.go
  log/logger.go
  log/logger_test.go
  log/root.go
  muxdb/internal/trie/cache.go
  muxdb/internal/trie/trie.go
  p2psrv/rpc/rpc.go
  p2psrv/server.go
  state/cached_object_test.go
  trie/proof_test.go
  tx/block_ref_test.go
  txpool/tx_pool.go
  txpool/tx_pool_test.go
Labels: enhancement

#778 chore: add additional metrics (websockets / node stats)
  api/metrics.go
  api/metrics_test.go
  api/subscriptions/subscriptions.go
  cmd/thor/node/metrics.go
  cmd/thor/node/node.go
  cmd/thor/node/packer_loop.go
  metrics/noop.go
  metrics/noop_test.go
  metrics/prometheus.go
  metrics/prometheus_test.go
  metrics/telemetry.go
  txpool/tx_pool.go
Labels: enhancement

#764 Update thor-upstream
  go.mod
  go.sum
Labels: dependencies
