Repository vechain/thor, pull requests merged in 2024-04, with the labels that each got.

#699 chore: update contributing docs
  .github/CONTRIBUTING.md
  .github/pull_request_template.md
  README.md
Labels: next release candidate

#691 Adds test for DeriveRoot function in trie
  trie/derive_root_test.go
Labels: next release candidate, testing

#687 Subscriptions test
  api/subscriptions/beat2_reader_test.go
  api/subscriptions/beat_reader_test.go
  api/subscriptions/block_reader_test.go
  api/subscriptions/event_reader_test.go
  api/subscriptions/pending_tx_test.go
  api/subscriptions/subscriptions.go
  api/subscriptions/subscriptions_test.go
  api/subscriptions/transfer_reader_test.go
  api/subscriptions/types_test.go
  txpool/tx_pool.go
Labels: next release candidate, testing

#686 Debug test
  api/debug/debug.go
  api/debug/debug_test.go
Labels: next release candidate, testing

#676 test: add test coverage for api/utils package
  api/utils/http_test.go
Labels: next release candidate, testing

#685 Enable e2e tests
  .github/workflows/on-master-commit.yaml
  .github/workflows/on-pull-request.yaml
  .github/workflows/test-e2e.yaml
Labels: testing, CICD

#705 Add docker security scan
  .github/workflows/on-master-commit.yaml
  .github/workflows/publish-docker-images.yaml
  .github/workflows/test.yaml
  Dockerfile
Labels: CICD

#708 Readme refactor
  README.md
  docs/CODE_OF_CONDUCT.md
  docs/CONTRIBUTING.md
  docs/SECURITY.md
  docs/assets/banner-dark-mode.png
  docs/assets/banner-light-mode.png
  docs/build.md
  docs/hosting-a-node.md
  docs/usage.md
Labels: documentation

#682 cmd: add genesis flag to solo, allow specifying a custom genesis file…
  cmd/thor/flags.go
  cmd/thor/main.go
  cmd/thor/utils.go
Labels: new feature

#696 improve txpool tests
  txpool/tx_pool_test.go
Labels: testing

#695 add tests for cmd/node/optimizer
  cmd/thor/optimizer/optimizer_test.go
Labels: testing

#712 improve doc, add genesis flag to solo
  README.md
  docs/hosting-a-node.md
  docs/usage.md
Labels: documentation

#688 Adds allowed-peers Flag
  cmd/thor/flags.go
  cmd/thor/main.go
  cmd/thor/utils.go
  p2psrv/server.go
  p2psrv/server_test.go
Labels: new feature
