Repository vechain/thor, pull requests merged in 2024-05, with the labels that each got.

#731 add GHA to check for license
  .github/workflows/license-check.yaml
  .github/workflows/on-master-commit.yaml
  .github/workflows/on-pull-request.yaml
  .licenserc.yaml
  Makefile
  thor/blocklist_test.go
  thor/fork_config_test.go
  thor/receipt_correction_test.go
  trie/derive_root_test.go
Labels: CICD

#716 test: add tests for shanghai new opcodes
  runtime/runtime_test.go
  thor/fork_config_test.go
  vm/jump_table_test.go
Labels: testing

#738 fix: relative links don't work with a proxy
  api/doc/stoplight-ui/index.html
  api/doc/swagger-ui/index.html
Labels: bug

#689 feat: add support for 'finalized' revision in accounts
  api/accounts/accounts.go
  api/accounts/accounts_test.go
  api/api.go
  api/blocks/blocks.go
  api/blocks/blocks_test.go
  api/blocks/types.go
  api/debug/debug.go
  api/debug/debug_test.go
  api/doc/thor.yaml
  api/utils/revisions.go
  api/utils/revisions_test.go
  bft/engine.go
Labels: new feature

#736 Builtin coverage
  builtin/authority/authority_test.go
Labels: testing

#734 Adding api-logs-enabled flag
  api/api.go
  api/request_logger.go
  api/request_logger_test.go
  cmd/thor/flags.go
  cmd/thor/main.go
Labels: new feature

#724 Cleanup p2p thor + add tests
  cmd/thor/main.go
  cmd/thor/p2p/bootstrap.go
  cmd/thor/p2p/p2p.go
  cmd/thor/p2p/p2p_test.go
  cmd/thor/utils.go
  p2psrv/options.go
  p2psrv/server.go
  test/datagen/net.go
  test/datagen/numbers.go
Labels: refactor

#740 Selectable block interval on solo
  cmd/thor/flags.go
  cmd/thor/main.go
  cmd/thor/solo/solo.go
  cmd/thor/solo/solo_test.go
  docs/usage.md
Labels: new feature

#671 Adding Metrics to the node
  api/accounts/accounts.go
  api/api.go
  api/blocks/blocks.go
  api/debug/debug.go
  api/events/events.go
  api/node/node.go
  api/subscriptions/subscriptions.go
  api/transactions/transactions.go
  api/transfers/transfers.go
  api/utils/http.go
  bft/engine.go
  bft/metrics.go
  block/block.go
  cmd/thor/flags.go
  cmd/thor/main.go
  cmd/thor/node/metrics.go
  cmd/thor/node/node.go
  cmd/thor/node/packer_loop.go
  cmd/thor/utils.go
  comm/handle_rpc.go
  docs/hosting-a-node.md
  docs/usage.md
  go.mod
  go.sum
  metrics/README.md
  metrics/noop.go
  metrics/noop_test.go
  metrics/prometheus.go
  metrics/prometheus_test.go
  metrics/telemetry.go
  p2psrv/metrics.go
  p2psrv/server.go
  thor/size.go
  tx/transaction.go
  tx/transaction_test.go
  txpool/metrics.go
  txpool/tx_pool.go
Labels: new feature

#742 remove flaky subscription test
  api/subscriptions/subscriptions_test.go
Labels: bug, testing
